USE [master]
GO
/****** Object:  Database [8BDAPI]    Script Date: 2/28/2020 2:32:05 PM ******/
CREATE DATABASE [8BDAPI]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'8BDAPI', FILENAME = N'D:\Program Files (x86)\MSSQL12.SQLEXPRESS\MSSQL\DATA\8BDAPI.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'8BDAPI_log', FILENAME = N'D:\Program Files (x86)\MSSQL12.SQLEXPRESS\MSSQL\DATA\8BDAPI_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [8BDAPI] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [8BDAPI].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [8BDAPI] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [8BDAPI] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [8BDAPI] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [8BDAPI] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [8BDAPI] SET ARITHABORT OFF 
GO
ALTER DATABASE [8BDAPI] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [8BDAPI] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [8BDAPI] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [8BDAPI] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [8BDAPI] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [8BDAPI] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [8BDAPI] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [8BDAPI] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [8BDAPI] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [8BDAPI] SET  DISABLE_BROKER 
GO
ALTER DATABASE [8BDAPI] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [8BDAPI] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [8BDAPI] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [8BDAPI] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [8BDAPI] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [8BDAPI] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [8BDAPI] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [8BDAPI] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [8BDAPI] SET  MULTI_USER 
GO
ALTER DATABASE [8BDAPI] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [8BDAPI] SET DB_CHAINING OFF 
GO
ALTER DATABASE [8BDAPI] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [8BDAPI] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [8BDAPI] SET DELAYED_DURABILITY = DISABLED 
GO
USE [8BDAPI]
GO
/****** Object:  Table [dbo].[entry]    Script Date: 2/28/2020 2:32:05 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[entry](
	[id] [int] NOT NULL,
	[author_id] [int] NOT NULL,
	[subject_id] [int] NOT NULL,
	[subject] [varchar](55) NOT NULL,
	[entry] [text] NOT NULL,
	[createDate] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[subject]    Script Date: 2/28/2020 2:32:06 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[subject](
	[id] [int] NOT NULL,
	[author_id] [int] NOT NULL,
	[subject] [text] NOT NULL,
	[isActive] [int] NOT NULL,
	[createDate] [datetime] NOT NULL,
	[updateDate] [datetime] NOT NULL,
	[BSHIU] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[entry] ADD  DEFAULT (getdate()) FOR [createDate]
GO
ALTER TABLE [dbo].[subject] ADD  DEFAULT (getdate()) FOR [createDate]
GO
ALTER TABLE [dbo].[subject] ADD  DEFAULT (getdate()) FOR [updateDate]
GO
USE [master]
GO
ALTER DATABASE [8BDAPI] SET  READ_WRITE 
GO
