USE [master]
GO
/****** Object:  Database [8BDAPI]    Script Date: 3/25/2020 12:02:12 PM ******/
CREATE DATABASE [8BDAPI]
GO
ALTER DATABASE [8BDAPI] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [8BDAPI].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [8BDAPI] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [8BDAPI] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [8BDAPI] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [8BDAPI] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [8BDAPI] SET ARITHABORT OFF 
GO
ALTER DATABASE [8BDAPI] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [8BDAPI] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [8BDAPI] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [8BDAPI] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [8BDAPI] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [8BDAPI] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [8BDAPI] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [8BDAPI] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [8BDAPI] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [8BDAPI] SET  DISABLE_BROKER 
GO
ALTER DATABASE [8BDAPI] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [8BDAPI] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [8BDAPI] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [8BDAPI] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [8BDAPI] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [8BDAPI] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [8BDAPI] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [8BDAPI] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [8BDAPI] SET  MULTI_USER 
GO
ALTER DATABASE [8BDAPI] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [8BDAPI] SET DB_CHAINING OFF 
GO
ALTER DATABASE [8BDAPI] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [8BDAPI] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [8BDAPI] SET DELAYED_DURABILITY = DISABLED 
GO
USE [8BDAPI]
GO
/****** Object:  Table [dbo].[entry]    Script Date: 3/25/2020 12:02:12 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[entry](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[authorId] [int] NULL,
	[subjectId] [int] NULL,
	[entry] [nvarchar](max) NULL,
	[createDate] [datetime] NULL,
	[lastUpdateDate] [datetime] NULL,
 CONSTRAINT [PK_entry] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[garbageentry]    Script Date: 3/25/2020 12:02:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[garbageentry](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[entryId] [int] NULL,
	[authorId] [int] NULL,
	[subjectId] [int] NULL,
	[subject] [varchar](55) NULL,
	[entry] [text] NULL,
	[createDate] [datetime] NULL,
	[lastUpdateDate] [datetime] NULL,
	[deletedDate] [datetime] NULL,
	[deletedFor] [text] NULL,
	[deletedById] [int] NULL,
 CONSTRAINT [PK_garbageentry] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[subject]    Script Date: 3/25/2020 12:02:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[subject](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[authorId] [int] NULL,
	[subject] [nvarchar](55) NULL,
	[isActive] [int] NULL,
	[createDate] [datetime] NULL,
	[updateDate] [datetime] NULL,
	[BSHIU] [varchar](5) NULL,
 CONSTRAINT [PK_subjecgt] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[user]    Script Date: 3/25/2020 12:02:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[user](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[username] [varchar](50) NULL,
	[password] [varchar](50) NULL,
	[email] [varchar](50) NULL,
	[activationToken] [varchar](8) NULL,
	[activationTokenValidTime] [datetime] NULL,
	[userLevel] [int] NULL,
	[isApproved] [int] NULL,
	[isActive] [int] NULL,
	[registerIp] [varchar](50) NULL,
	[registerDate] [datetime] NULL,
	[lastLoginDate] [datetime] NULL,
 CONSTRAINT [PK_Table_1] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[userlevel]    Script Date: 3/25/2020 12:02:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[userlevel](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[userLevel] [int] NULL,
	[userLevelInfo] [varchar](55) NULL,
 CONSTRAINT [PK_userlevel] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[vote]    Script Date: 3/25/2020 12:02:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[vote](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[authorId] [int] NULL,
	[voterId] [int] NULL,
	[entryId] [int] NULL,
	[type] [int] NULL,
	[voteDate] [datetime] NULL,
 CONSTRAINT [PK_vote] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[entry] ADD  CONSTRAINT [DF_entry_createDate]  DEFAULT (getdate()) FOR [createDate]
GO
ALTER TABLE [dbo].[entry] ADD  CONSTRAINT [DF_entry_lastUpdateDate]  DEFAULT (getdate()) FOR [lastUpdateDate]
GO
ALTER TABLE [dbo].[garbageentry] ADD  CONSTRAINT [DF_garbageentry_deletedDate]  DEFAULT (getdate()) FOR [deletedDate]
GO
ALTER TABLE [dbo].[subject] ADD  CONSTRAINT [DF_subjecgt_createDate]  DEFAULT (getdate()) FOR [createDate]
GO
ALTER TABLE [dbo].[subject] ADD  CONSTRAINT [DF_subjecgt_updateDate]  DEFAULT (getdate()) FOR [updateDate]
GO
ALTER TABLE [dbo].[subject] ADD  CONSTRAINT [DF_subjecgt_BSHIU]  DEFAULT ((0)) FOR [BSHIU]
GO
ALTER TABLE [dbo].[user] ADD  CONSTRAINT [DF_Table_1_registerDate]  DEFAULT (getdate()) FOR [registerDate]
GO
ALTER TABLE [dbo].[user] ADD  CONSTRAINT [DF_Table_1_lastLoginDate]  DEFAULT (getdate()) FOR [lastLoginDate]
GO
USE [master]
GO
ALTER DATABASE [8BDAPI] SET  READ_WRITE 
GO
